# ========================
# Pre_processing
# Author: Mohamed Salem
# ========================

In [ ]:
# Import libraries
# ------------------
import pandas as pd

In [ ]:
# Load Dataset
# ---------------
from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv

In [ ]:
df = pd.read_csv("data.csv", encoding='latin1')

In [ ]:
# --------------------
# Data Understanding
# --------------------

In [ ]:
print(df.shape)

(536641, 8)

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536641 entries, 0 to 536640
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    536641 non-null  object
 1   StockCode    536641 non-null  object
 2   Description  535187 non-null  object
 3   Quantity     536641 non-null  int64
 4   InvoiceDate  536641 non-null  object
 5   UnitPrice    536641 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      536641 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 32.8+ MB

In [ ]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  536641.000000  536641.000000  401604.000000
mean        9.620029       4.632656   15281.160818
std       219.130156      97.233118    1714.006089
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13939.000000
50%         3.000000       2.080000   15145.000000
75%        10.000000       4.130000   16784.000000
max     80995.000000   38970.000000   18287.000000

In [ ]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
dtype: int64

In [ ]:
df['Description']

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
536636            PACK OF 20 SPACEBOY NAPKINS
536637           CHILDREN'S APRON DOLLY GIRL
536638          CHILDRENS CUTLERY DOLLY GIRL
536639        CHILDRENS CUTLERY CIRCUS PARADE
536640          BAKING SET 9 PIECE RETROSPOT
Name: Description, Length: 536641, dtype: object

In [ ]:
# -----------------------
# Handle Missing Values
# -----------------------

In [ ]:
df.dropna(subset=['Description'])

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
536636,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
536637,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
536638,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
536639,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
536640,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [ ]:
df.isnull().mean()*100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.270945
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     25.163377
Country         0.000000
dtype: float64

In [ ]:
# ---------------
# Data Cleaning
# ---------------

In [ ]:
df=df.drop_duplicates()

In [ ]:
df=df[df['Quantity']>0]
df=df[df['UnitPrice']>0]

In [ ]:
# ----------------------
# Data Type Conversion
# ----------------------

In [ ]:
df['CustomerID']=df['CustomerID'].astype(str)

In [ ]:
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [ ]:
# ---------------------
# Feature Engineering
# ---------------------

In [ ]:
df['TotalPrice']=df['Quantity']*df['UnitPrice']

In [ ]:
# ------------------------
# Final Dataset Overview
# ------------------------

In [ ]:
print ("Final Dataset Shape:",df.shape)
df.head(10)

Final Dataset Shape: (524878, 9)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,15.30
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,25.50
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,54.08

In [ ]:
df.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
536631,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France,15.00
536632,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France,15.00
536633,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France,15.60
536634,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,23.40
536635,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
536636,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
536637,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
536638,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
536639,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
536640,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [ ]:
df.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
193205,553673,21672,WHITE SPOT RED CERAMIC DRAWER KNOB,12,2011-05-18 12:46:00,1.25,16814.0,United Kingdom,15.00
438081,574656,23103,JINGLE BELL HEART DECORATION,24,2011-11-06 11:36:00,1.65,16434.0,United Kingdom,39.60
132440,547789,21094,SET/6 RED SPOTTY PAPER PLATES,12,2011-03-25 12:04:00,0.85,14911.0,EIRE,10.20
307567,564150,20828,GLITTER BUTTERFLY CLIPS,12,2011-08-23 12:30:00,2.55,14936.0,Channel Islands,30.60
136850,548191,21656,RIDGED GLASS POSY VASE,1,2011-03-29 15:20:00,3.29,nan,United Kingdom,3.29
317452,564943,22632,HAND WARMER RED RETROSPOT,12,2011-08-31 13:23:00,2.10,17706.0,United Kingdom,25.20
206338,555093,22627,MINT KITCHEN SCALES,2,2011-05-31 13:15:00,8.50,12720.0,Germany,17.00
495130,578696,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-11-25 10:02:00,4.15,13985.0,United Kingdom,16.60
98856,544788,21497,FANCY FONTS BIRTHDAY WRAP,25,2011-02-23 12:18:00,0.42,13089.0,United Kingdom,10.50
142966,548735,21564,PINK HEART SHAPE LOVE BUCKET,1,2011-04-04 10:52:00,2.95,15039.0,United Kingdom,2.95

In [ ]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 524878 entries, 0 to 536640
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    524878 non-null  object
 1   StockCode    524878 non-null  object
 2   Description  524878 non-null  object
 3   Quantity     524878 non-null  int64
 4   InvoiceDate  524878 non-null  datetime64[ns]
 5   UnitPrice    524878 non-null  float64
 6   CustomerID   524878 non-null  object
 7   Country      524878 non-null  object
 8   TotalPrice   524878 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 40.0+ MB